name: 'Test Docker Image'
description: 'test Dockerfile for Hubble'
inputs:
#  test_dir:
#    description: the directory to run the tests
#    required: true
#    default: '.'
  outputs:
    exit_code:
      decription: 'exit successfully with 0'
      value: ${{ steps.test_docker.outputs.exit_code}}
runs:
  using: "composite"
  steps:
#    - run: echo testing ${{ inputs.test_dir}}
#      shell: bash
    - id: test_docker
      run: |
        ${{ github.action_path }}/test_docker.sh .
        echo "::set-output name=exit_code::$(echo $local_exit_code)"
      shell: bash